# Generated by Django 5.2.3 on 2025-06-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="shop.products",
            ),
        ),
    ]
