# Generated by Django 5.2.3 on 2025-07-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="tags",
            field=models.ManyToManyField(related_name="products", to="shop.tags"),
        ),
    ]
