# Generated by Django 5.2.3 on 2025-08-04 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="id",
        ),
        migrations.AlterField(
            model_name="payment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
