# Generated by Django 5.2.3 on 2025-08-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_remove_payment_id_alter_payment_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="shop.orders",
            ),
        ),
    ]
