# Generated by Django 5.2.3 on 2025-08-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_alter_payment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EUR", "Евро"),
                    ("USD", "Доллар"),
                    ("RUB", "Рубль"),
                    ("UAH", "Гривна"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
