# Generated by Django 5.2.3 on 2025-08-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_payment_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="name",
            field=models.CharField(default="Оплата заказа", max_length=100),
        ),
    ]
